### ISSUE TITLE
Database is not available via R3trans

### ISSUE THREAD

**Issue by aracelychavez** [sbcgua/sap-nw-abap-vagrant#17]
Everything was ok, and I havent done any change, till today starting sapnw, because I wanted to renew the key, I got a message :

Database is not available via R3trans.
----------------------------------
starting database NPL ...
Log File: /sybase/NPL/startdb.log

any idea? Thanks in advance!

**Comment by sbcgua** [comment]
I think that may have to do with sybase license, it run out of validaty range a month ago. This may impact the installation but I didn't try. https://blogs.sap.com/2018/08/30/as-abap-7.5x-ase-license-available/

**Comment by aracelychavez** [comment]
Oh I didn't know that! I'm gonna check for that side, then. Thank you Alex for all your help. I couldn't have had my demo without your amazing approach. Be healthy. :)
