### ISSUE TITLE
Some notes about docker

### ISSUE THREAD

**Issue by jfilak** [sbcgua/sap-nw-abap-vagrant#2]
> Ideologically docker is supposed to be stateless. Databases should be in volumes, not inside docker layer.

Ignore ideology, I have been running a docker container for 4 months. You can start it and stop it as you wish. It works like a VM.

**Comment by sbcgua** [comment]
Maybe I should soften the judgement in the readme :)
Docker is OK, I think it would be really good to reuse it's composability, like attach a pod with smtpserver, with HANA express for side car. That would be really cool.
But I just think that it needs more infrastructure. Well, **under Windows**. Separate host virtual machine, more memory, more storage, enabling the Hypervisor, blah blah ... I'm totally OK with it, but for new people it steepens the learning curve. Just imho.
Actually all the scripts in the repo easily transfered to docker so might be a good idea to make a docker sibling config. Would be really nice to compose it with HANA express.

**Comment by sbcgua** [comment]
fixed the readme a bit

**Comment by jfilak** [comment]
Nice, thank you for being so open-minded!
