### ISSUE TITLE
Option to specify a VM Name

### ISSUE THREAD

**Issue by bmml1** [sbcgua/sap-nw-abap-vagrant#5]
When trying to install a second instance there is an error message:
`A VirtualBox machine with the name 'Sap-nw752' already exists.
`

I would be cool to have the option to speficy the vm name as a command line option and be asked to give an alternative name if an instance with the default name already exists.

**Comment by sbcgua** [comment]
Good idea :+1:
Please try the latest version
```
vagrant --vm-name=HelloWorld up 
```
Also see the updated readme.
Should work, though I didn't test a lot. The name should be specifies for all subsequent runs ... although if you make a copy of vagrant folder for the second instance I guess it will be needed just on the first run ... not exactly sure, didn't try.

**Comment by bmml1** [comment]
This works just fine! In the additional feature section there should also be a hint to speficy the name if one wants to ssh on the machine / run the addon.  
e.g. `vagrant --vm-name=HelloWorld ssh -c "sudo /vagrant/scripts/install_addons.sh"`

Thanks :)

**Comment by sbcgua** [comment]
Good point. Done.

So if no more comments here, then I'm closing this one
